name: Terraform Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Create .env file
        run: |
          echo "TF_HTTP_PASSWORD=${{ steps.app-token.outputs.token }}" > .env
          echo "TF_VAR_github_token=${{ steps.app-token.outputs.token }}" >> .env
          echo "TF_VAR_github_org=${{ github.repository_owner }}" >> .env
          echo "TF_VAR_github_repo=${{ github.event.repository.name }}" >> .env

      - name: Build Docker image
        run: make build-image

      - name: Initialize Terraform
        run: make init

      - name: Validate Terraform
        run: make validate

      - name: Plan Terraform
        run: make plan

      - name: Post plan to PR
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: terraform-plan
          path: terraform/plan/terraform.txt

      - name: Apply Terraform
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: make apply
